name: Test Workflow
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for open pull requests
        id: check-pr
        run: |
          response=$(curl -s -H "Accept: application/vnd.github.v3+json" \
                          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository_owner }}:${{ github.ref_name }}")
          echo "response=$response" >> $GITHUB_ENV
          if [ "$response" == "[]" ]; then
            echo "No open pull requests for this branch."
          else
            echo "Open pull requests found for this branch."
            exit 1
          fi

      - name: Run tests
        if: ${{ steps.check-pr.outcome != 'failure' }}
        run: echo "Running tests..."
