name: No Push on PR

on:
  push:
  pull_request:

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Check if there is an open PR
        id: check-pr
        run: |
          PR_URL=$(gh pr list --base ${{ github.ref_name }} --state open --json url --jq '.[0].url')
          if [ -n "$PR_URL" ]; then
            echo "Pull request exists: $PR_URL"
            echo "pr_exists=true" >> $GITHUB_ENV
          else
            echo "No pull request exists for the branch."
            echo "pr_exists=false" >> $GITHUB_ENV

      - name: Fail if PR exists
        if: env.pr_exists == 'true'
        run: |
          echo "Push event is blocked because there is an open pull request."
          exit 1
