name: Test Workflow
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  set-target-branch:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      target_branch: ${{ steps.set-target-branch.outputs.target_branch }}
    steps:
      - name: Set target branch
        id: set-target-branch
        run: echo "target_branch=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if push to target branch in pull request
        if: ${{ github.event_name == 'push' && needs.set-target-branch.outputs.target_branch && needs.set-target-branch.outputs.target_branch == github.ref_name }}
        run: exit 1

      - name: Run tests
        run: echo "Running tests..."
