name: gitleaks
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  set-target-branch:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      target_branch: ${{ steps.set-target-branch.outputs.target_branch }}
    steps:
      - name: Set target branch
        id: set-target-branch
        run: echo "base_ref=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT

  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: echo variables
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo github.actor: ${{ github.actor }}
          echo github.base_ref: ${{ github.base_ref }}
          echo github.env: ${{ github.env }}
          echo github.event_name: ${{ github.event_name }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref: ${{ github.ref }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.ref_type: ${{ github.ref_type }}
          echo github.triggering_actor: ${{ github.triggering_actor }}
          echo github.workflow: ${{ github.workflow }}
          echo github.workflow_ref: ${{ github.workflow_ref }}
          echo github.event.pull_request: ${{ github.event.pull_request }}
          echo github.event: $EVENT_CONTEXT

      - name: Check if push to target branch in pull request
        if: ${{ github.event_name == 'push' && needs.set-target-branch.outputs.base_ref == 'main' }}
        run: echo "This is a push to the target branch in a pull request."

      - uses: shoptet/gitleaks-action@8bd842f1842723c6f77ea0ddf58bc2872eb073bb
        if: ${{ github.event_name == 'push' && needs.set-target-branch.outputs.base_ref == 'main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
