name: Test Workflow
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for open pull requests
        if: github.event_name == 'push'
        id: check-pr
        run: |
          response=$(curl -s -H "Accept: application/vnd.github.v3+json" \
                          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository_owner }}:${{ github.ref_name }}")
          echo "response=$(echo $response | jq length)" >> $GITHUB_OUTPUT

      - name: Run tests
        if: github.event_name == 'pull_request' || (github.event_name == 'push' && steps.check-pr.outputs.response == 0)
        run: echo "gitleaks running..."
